<?php

namespace Kostikas\GitLogger;

use Illuminate\Support\ServiceProvider;

class GitProvider extends ServiceProvider{




    public function boot(){
            $this->loadRoutesFrom(__DIR__.'/routes/web.php');
            $this->loadViewsFrom(__DIR__.'/views' , 'GitLogger');
            $this->mergeConfigFrom(__DIR__.'/config/config.php','gitlogger');

            $this->publishes([
                __DIR__.'/config/config.php' => config_path('config.php')
            ]);
    }




    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
